baseURL: "https://kazettique.github.io/"
languageCode: tw
title: Woody's Blog
theme: PaperMod
# enableEmoji: true
# copyright: Everything is mine # copyright custom message

defaultContentLanguage: tw

disableLanguages:
  - en
  - jp

languages:
  en:
    languageName: "English"
    languageAltTitle: English
    title: Woody's Blog
    weight: 1
    menu:
      main:
        # - name: Archive
        #   url: archives
        #   weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

    homeInfoParams:
      enabled: true
      title: Howdy, I'm Woody ğŸ‘‹
      imageUrl: "https://avatars.githubusercontent.com/u/42999338?v=4"
      imageTitle: avatar images
      imageWidth: 200
      imageHeight: 200
      content: I'm a front-end engineer exploring around with React, Vue and Angular in the gorgeous JavaScript world. =]
      # subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"

  tw:
    languageName: "ç¹é«”ä¸­æ–‡"
    languageAltTitle: English
    title: Woody's Blog
    weight: 2
    menu:
      main:
        # - name: å°å­˜
        #   url: archives
        #   weight: 5
        - name: æœå°‹
          url: search/
          weight: 10
        - name: æ¨™ç±¤
          url: tags/
          weight: 10
        - name: é¡åˆ¥
          url: categories/
          weight: 10

    homeInfoParams:
      enabled: true
      title: å“ˆå›‰ï½æˆ‘æ˜¯ Woody ğŸ‘‹
      imageUrl: "https://avatars.githubusercontent.com/u/42999338?v=4"
      imageTitle: avatar images
      imageWidth: 200
      imageHeight: 200
      content: æˆ‘æ˜¯åœ¨å¯¬å»£çš„ Javascript ä¸–ç•Œè£¡æ¢ç´¢ Reactã€Vue åŠ Angular çš„å‰ç«¯å·¥ç¨‹å¸« =]
      # subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"

  jp:
    languageName: "æ—¥æœ¬èª"
    languageAltTitle: Japan
    weight: 2
    title: Woody's Blog
    menu:
      main:
        # - name: ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–
        #   url: archives
        #   weight: 5
        - name: æ¤œç´¢
          url: search/
          weight: 10
        - name: ã‚¿ã‚°
          url: tags/
          weight: 10
        - name: ã‚«ãƒ†ã‚´ãƒª
          url: categories/
          weight: 10

    homeInfoParams:
      enabled: true
      title: ã“ã‚“ã«ã¡ã¯ã€Woodyã§ã™ ğŸ‘‹
      imageUrl: "https://avatars.githubusercontent.com/u/42999338?v=4"
      imageTitle: avatar images
      imageWidth: 200
      imageHeight: 200
      content: åºƒã„Javascriptã®ä¸–ç•Œã§ Reactã€Vueã¨Angularã‚’å‹‰å¼·ã—ã¦ã„ã¾ã™ =]
      # subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"

outputs:
  home:
    - HTML
    - RSS
    - JSON

# theme config
params:
  author: Woody Chang

  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true # show table of contents
  TocOpen: true # keep table of contents open by default
  # comments: false
  # images: ["papermod-cover.png"]

  # homeInfoParams:
  #   Title: Howdy, I'm Woody ğŸ‘‹
  #   Content: I'm a front-end engineer playing around with React, Vue and Angular in the gorgeous JavaScript world. =]
  #   subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"
  #   buttons:
  #     - name: Blog
  #       url: posts
  #     - name: Tags
  #       url: tags

  socialIcons: # optional
    - name: github
      url: https://github.com/kazettique
    - name: linkedin
      url: https://www.linkedin.com/in/woody-chang-508b38150/
    - name: instagram
      url: https://www.instagram.com/kazettique/
    - name: email
      url: mailto:kazettique@gmail.com

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
